tasks:
   - name: Backend
     init: yarn
     command: yarn start
   - name: FrontEnd
     init: |
        cd front
        yarn
     command: yarn start
ports:
   - port: 5000
     visibility: public
     onOpen: ignore
   - port: 3000
     visibility: public
     onOpen: ignore
