tasks:
   - name: Server
     init: yarn
     command: yarn start
   - name: Client
     init: cd client && yarn
     command: yarn start
ports:
   - port: 5000
     visibility: public
     onOpen: ignore
   - port: 3000
     visibility: public
     onOpen: ignore
