tasks:
   - name: Server
     init: npm
     command: npm start
   - name: Client
     init: cd client && npm
     command: cd client && npm start
ports:
   - port: 5000
     visibility: public
     onOpen: ignore
   - port: 3000
     visibility: public
     onOpen: ignore
