tasks:
   - name: Server
     init: npm i
   - name: Client
     init: cd client && npm i
ports:
   - port: 5000
     visibility: public
     onOpen: ignore
   - port: 3000
     visibility: public
     onOpen: ignore
