tasks:
   - name: Server
     command: npm i
   - name: Client
     command: cd client && npm i
ports:
   - port: 5000
     visibility: public
     onOpen: ignore
   - port: 3000
     visibility: public
     onOpen: ignore
