tasks:
   - name: Server
     before: npm i
   - name: Client
     before: cd client && npm i
ports:
   - port: 5000
     visibility: public
     onOpen: ignore
   - port: 3000
     visibility: public
     onOpen: ignore
